import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Minus, Plus, Trash2, Tag, AlertCircle, MapPin } from "lucide-react";
import { validateDelivery, validateOffer } from "../services/api";
import { useApp } from "../context/AppContext";

export default function Cart(){
  const {cart,updateCartQty,removeFromCart,products,settings}=useApp(); const navigate=useNavigate();
  const [code,setCode]=useState(""),[offer,setOffer]=useState(null),[offerError,setOfferError]=useState(""),[address,setAddress]=useState(""),[deliveryCheck,setDeliveryCheck]=useState({eligible:false,fee:0,message:""}),[checkingDelivery,setCheckingDelivery]=useState(false);
  const checked=useMemo(()=>cart.map(item=>{
    const live=products.find(p=>p.ProductID===item.ProductID);
    const livePrice=live?(live.Category==="Cake"?Number(live.PricePer500g||0)*(Number(item.Weight||0)/500):Number(live.PricePerPiece||0)):Number(item.ItemPrice||0);
    const stock=live?.Category==="Cake"?(live.stock||[]).find(x=>Number(x.Weight??x.weight)===Number(item.Weight||0)):null;
    const available=live?.Category==="Cake"?Number(stock?.UnitsAvailable??stock?.units??0):(live?.InStock==="Y"?999999:0);
    return {...item,live,livePrice,available,stalePrice:live&&Math.abs(livePrice-Number(item.ItemPrice||0))>0.001,staleStock:live&&Number(item.Qty||0)>available};
  }),[cart,products]);
  const subtotal=checked.reduce((s,x)=>s+Number(x.livePrice||x.ItemPrice||0)*Number(x.Qty||0),0); const candleBoxes=checked.reduce((s,x)=>s+Number(x.CandleBoxes||0),0); const candleCost=candleBoxes*Number(settings.CandleBoxPrice||5); const delivery=deliveryCheck.eligible?Number(settings.DeliveryFeeFlat||60):0; const discount=offer?.discount||0; const total=Math.max(0,subtotal+candleCost+delivery-discount);
  useEffect(()=>{setOffer(null);setOfferError("")},[subtotal]);
  useEffect(()=>{if(!address.trim()){setDeliveryCheck({eligible:false,fee:0,message:""});return;}const timer=setTimeout(async()=>{try{setCheckingDelivery(true);setDeliveryCheck(await validateDelivery({address}))}catch(e){setDeliveryCheck({eligible:false,fee:0,message:e.message})}finally{setCheckingDelivery(false)}},500);return()=>clearTimeout(timer)},[address]);
  const apply=async()=>{const result=await validateOffer(code,subtotal);if(result.valid){setOffer(result);setOfferError("")}else{setOffer(null);setOfferError(result.message)}};
  if(!cart.length)return <section className="section"><div className="container empty-state"><div className="empty-icon">🧁</div><h1>Your cart is empty</h1><p>Pick something sweet and come back here when you're ready.</p><Link className="btn btn-primary" to="/menu/cakes">Explore the menu <ArrowRight size={17}/></Link></div></section>;
  return <section className="section"><div className="container"><div className="page-title-row"><div><span className="eyebrow">Your order</span><h1>Cart</h1></div><span className="muted">{cart.length} line item{cart.length!==1?"s":""}</span></div><div className="cart-layout"><div className="cart-list">
    {checked.map(item=><div className="cart-item" key={item.lineId}><div className={`cart-thumb ${item.Category?.toLowerCase()}`}><img src={item.ImageURL} alt="" onError={e=>e.currentTarget.style.display="none"}/></div><div className="cart-item-info"><h3>{item.Name}</h3><p>{item.Category==="Cake"?`${item.Weight}g · ₹${item.livePrice} each`:`₹${item.livePrice} each`}{item.stalePrice&&<small className="form-error">Price updated from ₹{item.ItemPrice} to ₹{item.livePrice}. Checkout will use the current price.</small>}{item.staleStock&&<small className="form-error">Only {item.available} unit(s) remain at this weight.</small>}</p>{item.CakeMessage&&<small>Message: {item.CakeMessage}</small>}{item.CandleBoxes>0&&<small>Candles: {item.CandleBoxes} box{item.CandleBoxes>1?"es":""}</small>}{!item.live&&<small className="form-error">This product is no longer available.</small>}</div><div className="cart-item-actions"><div className="stepper"><button onClick={()=>updateCartQty(item.lineId,item.Qty-1)}><Minus size={14}/></button><strong>{item.Qty}</strong><button onClick={()=>updateCartQty(item.lineId,item.Qty+1)}><Plus size={14}/></button></div><strong>₹{(Number(item.livePrice)*Number(item.Qty)).toLocaleString("en-IN")}</strong><button className="icon-btn danger" onClick={()=>removeFromCart(item.lineId)}><Trash2 size={16}/></button></div></div>)}
  </div><aside className="summary-card"><h3>Order summary</h3><div className="offer-box"><div className="offer-input"><Tag size={16}/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Offer code"/><button onClick={apply}>Apply</button></div>{offer&&<div className="offer-success">Offer {offer.code} applied · −₹{offer.discount}</div>}{offerError&&<div className="offer-error"><AlertCircle size={14}/>{offerError}</div>}</div>
    <label className="summary-address"><span><MapPin size={15}/> Delivery address (optional)</span><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Enter address to check delivery"/><small>{checkingDelivery?"Checking delivery radius…":deliveryCheck.message||`Delivery is ₹${settings.DeliveryFeeFlat} within ${settings.DeliveryRadiusKm} km.`}</small></label>
    <div className="summary-lines"><span>Subtotal <b>₹{subtotal.toLocaleString("en-IN")}</b></span><span>Candles <b>₹{candleCost}</b></span><span>Discount <b>−₹{discount}</b></span><span>Delivery <b>{delivery?`₹${delivery}`:"—"}</b></span></div><div className="summary-total"><span>Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><button className="btn btn-primary wide" disabled={checked.some(x=>!x.live||x.staleStock)||(address.trim()&&!deliveryCheck.eligible)} onClick={()=>navigate("/checkout",{state:{address,deliveryCheck,offer}})}>Proceed to Checkout <ArrowRight size={17}/></button><p className="tax-note">Tax is included in listed prices. Custom cakes never enter the cart.</p>
  </aside></div></div></section>;
}
