import { useMemo, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { ArrowRight, Check, CreditCard, MapPin, Store } from "lucide-react";
import { createCatalogOrder, validateBooking, validateDelivery } from "../services/api";
import { useApp } from "../context/AppContext";

function getDateBounds(minHours,maxDays){const now=new Date();const earliest=new Date(now.getTime()+minHours*60*60*1000);const max=new Date(now.getTime()+maxDays*24*60*60*1000);return{min:earliest.toISOString().slice(0,10),max:max.toISOString().slice(0,10)}}
export default function Checkout(){
  const {cart,settings,clearCart}=useApp();const navigate=useNavigate();const location=useLocation();const [step,setStep]=useState(1);const [status,setStatus]=useState("");
  const [form,setForm]=useState({fulfillment:"Pickup",paymentMode:"Pay at Store",name:"",phone:"",email:"",address:location.state?.address||"",occasion:"Birthday",date:"",time:"",notes:""});
  const [deliveryCheck,setDeliveryCheck]=useState(location.state?.deliveryCheck||null);
  const bounds=getDateBounds(Number(settings.MinLeadTimeHours||2),Number(settings.MaxLeadTimeDays||10));
  const subtotal=cart.reduce((s,x)=>s+Number(x.ItemPrice||0)*Number(x.Qty||0),0);const candleBoxCount=cart.reduce((s,x)=>s+Number(x.CandleBoxes||0),0);const candle=subtotal>=0?candleBoxCount*Number(settings.CandleBoxPrice||5):0;const delivery=form.fulfillment==="Delivery"?Number(settings.DeliveryFeeFlat||60):0;const discount=location.state?.offer?.discount||0;const total=Math.max(0,subtotal+candle+delivery-discount);
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const canNext=step===1?true:step===2?Boolean(form.name.trim()&&form.phone.trim()&&form.email.trim()&&form.date&&form.time&&form.occasion.trim()&&(form.fulfillment==="Pickup"||form.address.trim())):true;
  const chooseFulfillment=mode=>{set("fulfillment",mode);if(mode==="Delivery")set("paymentMode","Online");else set("paymentMode","Pay at Store");};
  const submit=async()=>{setStatus("");try{const booking=await validateBooking(form.date,form.time);if(booking?.valid===false)throw new Error(booking.message||"Please choose a valid booking slot.");let check=deliveryCheck;if(form.fulfillment==="Delivery"){check=await validateDelivery({address:form.address});setDeliveryCheck(check);if(!check.eligible)throw new Error(check.message||"Delivery is not available for this address.");}const result=await createCatalogOrder({...form,total,items:cart,offer:location.state?.offer,deliveryEligible:form.fulfillment==="Delivery"?check.eligible:false,deliveryDistanceKm:check?.distanceKm||null});clearCart();navigate(`/order-confirmation?type=catalog&id=${encodeURIComponent(result.orderId)}`,{state:{orderId:result.orderId,total}})}catch(e){setStatus(e.message||"Unable to place the order.")}};
  if(!cart.length)return <section className="section"><div className="container empty-state"><h2>Your cart is empty</h2><Link to="/menu/cakes" className="btn btn-primary">Shop now</Link></div></section>;
  return <section className="section"><div className="container checkout"><div className="breadcrumbs"><Link to="/cart">Cart</Link><ArrowRight size={14}/><strong>Checkout</strong></div><div className="checkout-steps">{["Fulfillment","Details","Payment","Confirmation"].map((x,i)=><div key={x} className={step===i+1?"step active":step>i+1?"step done":"step"}><span>{step>i+1?<Check size={14}/>:i+1}</span>{x}</div>)}</div>
    {step===1&&<div className="checkout-card"><div className="checkout-card-head"><span className="eyebrow">Step 1</span><h1>How would you like to receive it?</h1></div><div className="choice-grid"><button className={form.fulfillment==="Pickup"?"choice large selected":"choice large"} onClick={()=>chooseFulfillment("Pickup")}><Store/><strong>Store Pickup</strong><span>Pay in person at pickup. Online pickup payment can be enabled when a gateway is configured.</span></button><button className={form.fulfillment==="Delivery"?"choice large selected":"choice large"} onClick={()=>chooseFulfillment("Delivery")}><MapPin/><strong>Delivery</strong><span>₹{settings.DeliveryFeeFlat} flat fee within {settings.DeliveryRadiusKm} km. Online payment required.</span></button></div><div className="checkout-actions"><Link to="/cart" className="btn btn-ghost">Back to cart</Link><button className="btn btn-primary" onClick={()=>setStep(2)}>Continue <ArrowRight size={17}/></button></div></div>}
    {step===2&&<div className="checkout-card"><div className="checkout-card-head"><span className="eyebrow">Step 2</span><h1>Your details & booking</h1></div><div className="form-grid"><label>Name<input maxLength={120} value={form.name} onChange={e=>set("name",e.target.value)}/></label><label>Contact number<input maxLength={30} value={form.phone} onChange={e=>set("phone",e.target.value)}/></label><label>Email<input type="email" maxLength={160} value={form.email} onChange={e=>set("email",e.target.value)}/></label><label>Occasion<input maxLength={100} value={form.occasion} onChange={e=>set("occasion",e.target.value)}/></label><label>Date<input type="date" min={bounds.min} max={bounds.max} value={form.date} onChange={e=>set("date",e.target.value)}/><small className="field-note">Minimum {settings.MinLeadTimeHours} hours ahead · maximum {settings.MaxLeadTimeDays} days.</small></label><label>Time<input type="time" min={settings.ShopOpenTime} max={settings.ShopCloseTime} value={form.time} onChange={e=>set("time",e.target.value)}/><small className="field-note">Shop hours: {settings.ShopOpenTime}–{settings.ShopCloseTime}.</small></label></div>{form.fulfillment==="Delivery"&&<label><MapPin size={15}/> Delivery address<input maxLength={500} value={form.address} onChange={e=>set("address",e.target.value)} placeholder="Enter the delivery address"/><small className="field-note">The backend verifies the address against the {settings.DeliveryRadiusKm} km delivery radius.</small></label>}<label>Additional notes<textarea rows="4" maxLength={2000} value={form.notes} onChange={e=>set("notes",e.target.value)} placeholder="Anything the shop should know?"/></label><div className="checkout-actions"><button className="btn btn-ghost" onClick={()=>setStep(1)}>Back</button><button className="btn btn-primary" disabled={!canNext} onClick={()=>setStep(3)}>Continue <ArrowRight size={17}/></button></div></div>}
    {step===3&&<div className="checkout-card"><div className="checkout-card-head"><span className="eyebrow">Step 3</span><h1>{form.paymentMode==="Pay at Store"?"Confirm pickup":"Payment"}</h1></div>{form.paymentMode==="Pay at Store"?<div className="pay-info"><Store size={28}/><h3>Pay in person at pickup</h3><p>Your order is written immediately with payment status “Awaiting Payment at Pickup”.</p></div>:<div className="pay-info"><CreditCard size={28}/><h3>Online payment</h3><p>The payment gateway is not finalized yet. Online delivery orders cannot be placed until the gateway is connected.</p></div>}<div className="mini-total"><span>Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div>{status&&<div className="form-error">{status}</div>}<div className="checkout-actions"><button className="btn btn-ghost" onClick={()=>setStep(2)}>Back</button><button className="btn btn-primary" onClick={submit} disabled={form.paymentMode==="Online"}>{form.paymentMode==="Pay at Store"?"Confirm order":"Continue to payment"}<ArrowRight size={17}/></button></div></div>}
  </div></section>;
}
